name: Build Darwin

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  binding:
    # macos-11.0 is not available for all, so for now still use macos-10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - name: Build
        run: make binding_darwin_github_actions_limit_macos
      - name: Compress
        run: tar -czvf output.tar.gz -C output/binding/darwin .
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: libopenpgp_bridge_darwin_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true