name: Build Protobuf

on:
  workflow_dispatch:
  push:
    paths:
      - '**.proto'
    tags:
      - "v*"

jobs:
  dart:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        run: sudo apt install -y protobuf-compiler
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build
        run: |
          export PATH="$PATH":"$FLUTTER_HOME/.pub-cache/bin"
          make proto_dart_deps
          make proto_dart
      - name: Compress
        run: tar -czvf output.tar.gz -C output/dart .
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: protobuf_libopenpgp_bridge_dart_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: protobuf_libopenpgp_bridge_dart
          path: output.tar.gz
  go:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        run: sudo apt install -y protobuf-compiler
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          make proto_go_deps
          make proto_go
      - name: Compress
        run: tar -czvf output.tar.gz -C bridge/model .
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: protobuf_libopenpgp_bridge_go_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: protobuf_libopenpgp_bridge_go
          path: output.tar.gz